### ISSUE TITLE
Windows bug

### ISSUE THREAD

**Issue by vwxyzjn** [pekaalto/sc2aibot#1] opened 2017-11-11 05:33 UTC
Hi, thanks for reimplementing Deepmind's algorithm. However, it does not work on windows...

I am using tensorflow 1.3 and when I try to run it, the multiprocessing module seems to go wrong. See

![image](https://user-images.githubusercontent.com/5555347/32686685-f647bcba-c677-11e7-93f9-467b2fd39133.png)

Any help would be appreciated

**Comment by vwxyzjn** [comment] 2017-11-11 05:38
Is it possible for you to build you project by using [pipenv](https://github.com/kennethreitz/pipenv)? The reproducibility of your project could be greatly improved.

**Comment by pekaalto** [comment] 2017-11-11 12:08
I see. Unfortunately, I have no idea what the problem is about and I don't have windows machine to debug. So I can't help here. 

But about pipenv will take a look later.

**Comment by pekaalto** [comment] 2017-11-17 11:06
Should be fixed in the latest version. Please re-open if it's not.

**Closed as completed by pekaalto** 2017-11-17 11:06 UTC
